#!/usr/bin/env node
/**
 * record-browser.ts — Playwright records a deterministic Basescan tour.
 *
 * Usage:
 *   pnpm record:browser -- --phase 1.5b --tx 0xabc123…
 *
 * Output: public/captures/<phase>-browser.webm
 * Then a Remotion composition can <Video src={staticFile('captures/<phase>-browser.webm')} />.
 */

import { chromium } from "playwright";
import { mkdirSync } from "node:fs";
import { resolve } from "node:path";
import { config } from "dotenv";

config();

const arg = (name: string): string | undefined => {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 ? process.argv[i + 1] : undefined;
};

const phase = arg("phase") ?? "1.5a";
const tx = arg("tx") ?? process.env.DEMO_TX_HASH;
const address = arg("address") ?? process.env.DEMO_SETTLEMENT_ADDRESS;

if (!tx) {
  console.error("missing --tx <hash> (or DEMO_TX_HASH in .env)");
  process.exit(1);
}

const outDir = resolve("public/captures");
mkdirSync(outDir, { recursive: true });

const main = async () => {
  console.log(`recording browser tour for phase=${phase} tx=${tx.slice(0, 12)}…`);

  const browser = await chromium.launch({ headless: true });
  const context = await browser.newContext({
    viewport: { width: 1920, height: 1080 },
    recordVideo: { dir: outDir, size: { width: 1920, height: 1080 } },
    deviceScaleFactor: 2,
  });

  const page = await context.newPage();

  // Tour 1 — tx detail
  await page.goto(`https://sepolia.basescan.org/tx/${tx}`, { waitUntil: "networkidle" });
  await page.waitForTimeout(2500);

  // Smooth scroll to expose all fields
  await page.evaluate(() => {
    return new Promise<void>((res) => {
      const start = window.scrollY;
      const target = 400;
      const dur = 2000;
      const t0 = performance.now();
      const tick = (now: number) => {
        const p = Math.min(1, (now - t0) / dur);
        const eased = 1 - Math.pow(1 - p, 3);
        window.scrollTo(0, start + (target - start) * eased);
        if (p < 1) requestAnimationFrame(tick);
        else res();
      };
      requestAnimationFrame(tick);
    });
  });
  await page.waitForTimeout(1500);

  // Tour 2 — settlement address overview
  if (address) {
    await page.goto(`https://sepolia.basescan.org/address/${address}`, { waitUntil: "networkidle" });
    await page.waitForTimeout(2500);
  }

  await context.close();
  await browser.close();

  console.log(`capture written to ${outDir}/`);
  console.log(`(filename is generated by Playwright; rename to ${phase}-browser.webm if you want to reference it from Remotion)`);
};

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
